-- MySQL Script generated by MySQL Workbench
-- Mon Dec  9 19:04:30 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema PRONTOMUEBLE
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PRONTOMUEBLE` DEFAULT CHARACTER SET utf8 ;
USE `PRONTOMUEBLE` ;

-- -----------------------------------------------------
-- Table `PRONTOMUEBLE`.`Administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PRONTOMUEBLE`.`Administrador` (
  `idAdministrador` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(100) NOT NULL,
  `identificacion` VARCHAR(10) NOT NULL,
  `clave` VARCHAR(100) NOT NULL,
  `img` VARCHAR(45) NULL,
  PRIMARY KEY (`idAdministrador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PRONTOMUEBLE`.`Tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PRONTOMUEBLE`.`Tipo` (
  `idTipo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PRONTOMUEBLE`.`Mueble`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PRONTOMUEBLE`.`Mueble` (
  `idMueble` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `img` VARCHAR(45) NULL,
  `administrador_idAdministrador` INT NOT NULL,
  `idTipo` INT NOT NULL,
  PRIMARY KEY (`idMueble`),
  INDEX `fk_Mueble_Administrador1_idx` (`administrador_idAdministrador` ASC),
  INDEX `fk_Mueble_Tipo1_idx` (`Tipo_idTipo` ASC),
  CONSTRAINT `fk_Mueble_Administrador1`
    FOREIGN KEY (`administrador_idAdministrador`)
    REFERENCES `PRONTOMUEBLE`.`Administrador` (`idAdministrador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mueble_Tipo1`
    FOREIGN KEY (`Tipo_idTipo`)
    REFERENCES `PRONTOMUEBLE`.`Tipo` (`idTipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PRONTOMUEBLE`.`Proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PRONTOMUEBLE`.`Proveedor` (
  `idProveedor` INT NOT NULL AUTO_INCREMENT,
  `personaContacto` VARCHAR(45) NOT NULL,
  `razonSocial` VARCHAR(100) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `nit` VARCHAR(45) NOT NULL,
  `img` VARCHAR(45) NULL,
  `administrador_idAdministrador` INT NOT NULL,
  PRIMARY KEY (`idProveedor`),
  INDEX `fk_Proveedor_Administrador1_idx` (`administrador_idAdministrador` ASC),
  CONSTRAINT `fk_Proveedor_Administrador1`
    FOREIGN KEY (`administrador_idAdministrador`)
    REFERENCES `PRONTOMUEBLE`.`Administrador` (`idAdministrador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PRONTOMUEBLE`.`PedidoMueble`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PRONTOMUEBLE`.`PedidoMueble` (
  `cantidad` INT NOT NULL,
  `precio` DOUBLE NOT NULL,
  `proveedor_idProveedor` INT NOT NULL,
  `mueble_idMueble` INT NOT NULL,
  PRIMARY KEY (`proveedor_idProveedor`, `mueble_idMueble`),
  INDEX `fk_ProveedorMueble_Mueble1_idx` (`mueble_idMueble` ASC),
  CONSTRAINT `fk_ProveedorMueble_Proveedor`
    FOREIGN KEY (`proveedor_idProveedor`)
    REFERENCES `PRONTOMUEBLE`.`Proveedor` (`idProveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProveedorMueble_Mueble1`
    FOREIGN KEY (`mueble_idMueble`)
    REFERENCES `PRONTOMUEBLE`.`Mueble` (`idMueble`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PRONTOMUEBLE`.`TelefonoP`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PRONTOMUEBLE`.`TelefonoP` (
  `idTelefonoP` BIGINT NOT NULL,
  `proveedor_idProveedor` INT NOT NULL,
  PRIMARY KEY (`idTelefonoP`),
  INDEX `fk_TelefonoP_Proveedor1_idx` (`proveedor_idProveedor` ASC),
  CONSTRAINT `fk_TelefonoP_Proveedor1`
    FOREIGN KEY (`proveedor_idProveedor`)
    REFERENCES `PRONTOMUEBLE`.`Proveedor` (`idProveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PRONTOMUEBLE`.`Propiedad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PRONTOMUEBLE`.`Propiedad` (
  `idPropiedad` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `tipo_idTipo` INT NOT NULL,
  PRIMARY KEY (`idPropiedad`),
  INDEX `fk_Propiedad_Tipo1_idx` (`tipo_idTipo` ASC),
  CONSTRAINT `fk_Propiedad_Tipo1`
    FOREIGN KEY (`tipo_idTipo`)
    REFERENCES `PRONTOMUEBLE`.`Tipo` (`idTipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PRONTOMUEBLE`.`PropiedadMueble`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PRONTOMUEBLE`.`PropiedadMueble` (
  `descripcion` VARCHAR(45) NOT NULL,
  `propiedad_idPropiedad` INT NOT NULL,
  `mueble_idMueble` INT NOT NULL,
  PRIMARY KEY (`propiedad_idPropiedad`, `mueble_idMueble`),
  INDEX `fk_PropiedadMueble_Mueble1_idx` (`mueble_idMueble` ASC),
  CONSTRAINT `fk_PropiedadMueble_Propiedad1`
    FOREIGN KEY (`propiedad_idPropiedad`)
    REFERENCES `PRONTOMUEBLE`.`Propiedad` (`idPropiedad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PropiedadMueble_Mueble1`
    FOREIGN KEY (`mueble_idMueble`)
    REFERENCES `PRONTOMUEBLE`.`Mueble` (`idMueble`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PRONTOMUEBLE`.`Vendedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PRONTOMUEBLE`.`Vendedor` (
  `idVendedor` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(100) NOT NULL,
  `identificacion` VARCHAR(10) NOT NULL,
  `clave` VARCHAR(100) NOT NULL,
  `img` VARCHAR(45) NULL,
  `administrador_idAdministrador` INT NOT NULL,
  PRIMARY KEY (`idVendedor`),
  INDEX `fk_Vendedor_Administrador1_idx` (`administrador_idAdministrador` ASC),
  CONSTRAINT `fk_Vendedor_Administrador1`
    FOREIGN KEY (`administrador_idAdministrador`)
    REFERENCES `PRONTOMUEBLE`.`Administrador` (`idAdministrador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PRONTOMUEBLE`.`TelefonoV`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PRONTOMUEBLE`.`TelefonoV` (
  `idTelefonoV` BIGINT NOT NULL,
  `vendedor_idVendedor` INT NOT NULL,
  PRIMARY KEY (`idTelefonoV`),
  INDEX `fk_TelefonoV_Vendedor1_idx` (`vendedor_idVendedor` ASC),
  CONSTRAINT `fk_TelefonoV_Vendedor1`
    FOREIGN KEY (`vendedor_idVendedor`)
    REFERENCES `PRONTOMUEBLE`.`Vendedor` (`idVendedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PRONTOMUEBLE`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PRONTOMUEBLE`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(100) NOT NULL,
  `identificacion` VARCHAR(10) NOT NULL,
  `fechaCreacion` DATE NOT NULL,
  `vendedor_idVendedor` INT NOT NULL,
  PRIMARY KEY (`idCliente`),
  INDEX `fk_Cliente_Vendedor1_idx` (`vendedor_idVendedor` ASC),
  CONSTRAINT `fk_Cliente_Vendedor1`
    FOREIGN KEY (`vendedor_idVendedor`)
    REFERENCES `PRONTOMUEBLE`.`Vendedor` (`idVendedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PRONTOMUEBLE`.`Cotizacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PRONTOMUEBLE`.`Cotizacion` (
  `cantidad` INT NOT NULL,
  `cliente_idCliente` INT NOT NULL,
  `vendedor_idVendedor` INT NOT NULL,
  `proveedorMueble_Proveedor_idProveedor` INT NOT NULL,
  `proveedorMueble_Mueble_idMueble` INT NOT NULL,
  PRIMARY KEY (`cliente_idCliente`, `vendedor_idVendedor`, `proveedorMueble_Proveedor_idProveedor`, `proveedorMueble_Mueble_idMueble`),
  INDEX `fk_Cotizacion_Cliente1_idx` (`cliente_idCliente` ASC),
  INDEX `fk_Cotizacion_Vendedor1_idx` (`vendedor_idVendedor` ASC),
  INDEX `fk_Cotizacion_ProveedorMueble1_idx` (`proveedorMueble_Proveedor_idProveedor` ASC, `proveedorMueble_Mueble_idMueble` ASC),
  CONSTRAINT `fk_Cotizacion_Cliente1`
    FOREIGN KEY (`cliente_idCliente`)
    REFERENCES `PRONTOMUEBLE`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cotizacion_Vendedor1`
    FOREIGN KEY (`vendedor_idVendedor`)
    REFERENCES `PRONTOMUEBLE`.`Vendedor` (`idVendedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cotizacion_ProveedorMueble1`
    FOREIGN KEY (`proveedorMueble_Proveedor_idProveedor` , `proveedorMueble_Mueble_idMueble`)
    REFERENCES `PRONTOMUEBLE`.`PedidoProveedor` (`Proveedor_idProveedor` , `Mueble_idMueble`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PRONTOMUEBLE`.`Factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PRONTOMUEBLE`.`Factura` (
  `idFactura` INT NOT NULL AUTO_INCREMENT,
  `cantidadTotal` INT NOT NULL,
  `subTotal` DOUBLE NOT NULL,
  `fechaCreacion` DATE NOT NULL,
  `horaCreacion` TIME NOT NULL,
  `iva` INT NOT NULL,
  `total` DOUBLE NOT NULL,
  `vendedor_idVendedor` INT NOT NULL,
  `cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idFactura`),
  INDEX `fk_Factura_Vendedor1_idx` (`vendedor_idVendedor` ASC),
  INDEX `fk_Factura_Cliente1_idx` (`cliente_idCliente` ASC),
  CONSTRAINT `fk_Factura_Vendedor1`
    FOREIGN KEY (`vendedor_idVendedor`)
    REFERENCES `PRONTOMUEBLE`.`Vendedor` (`idVendedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Factura_Cliente1`
    FOREIGN KEY (`cliente_idCliente`)
    REFERENCES `PRONTOMUEBLE`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PRONTOMUEBLE`.`DetalleFactura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PRONTOMUEBLE`.`DetalleFactura` (
  `cantidad` INT NOT NULL,
  `precio` DOUBLE NOT NULL,
  `factura_idFactura` INT NOT NULL,
  `proveedorMueble_Proveedor_idProveedor` INT NOT NULL,
  `proveedorMueble_Mueble_idMueble` INT NOT NULL,
  PRIMARY KEY (`factura_idFactura`, `proveedorMueble_Proveedor_idProveedor`, `proveedorMueble_Mueble_idMueble`),
  INDEX `fk_DetalleFactura_Factura1_idx` (`factura_idFactura` ASC),
  INDEX `fk_MuebleFactura_ProveedorMueble1_idx` (`proveedorMueble_Proveedor_idProveedor` ASC, `proveedorMueble_Mueble_idMueble` ASC),
  CONSTRAINT `fk_DetalleFactura_Factura1`
    FOREIGN KEY (`factura_idFactura`)
    REFERENCES `PRONTOMUEBLE`.`Factura` (`idFactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MuebleFactura_ProveedorMueble1`
    FOREIGN KEY (`proveedorMueble_Proveedor_idProveedor` , `proveedorMueble_Mueble_idMueble`)
    REFERENCES `PRONTOMUEBLE`.`PedidoProveedor` (`Proveedor_idProveedor` , `Mueble_idMueble`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PRONTOMUEBLE`.`TelefonoC`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PRONTOMUEBLE`.`TelefonoC` (
  `idTelefonoC` BIGINT NOT NULL,
  `cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idTelefonoC`),
  INDEX `fk_TelefonoC_Cliente1_idx` (`cliente_idCliente` ASC),
  CONSTRAINT `fk_TelefonoC_Cliente1`
    FOREIGN KEY (`cliente_idCliente`)
    REFERENCES `PRONTOMUEBLE`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
